user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  log_format json_combined escape=json '{"time":"$time_iso8601","remote_addr":"$remote_addr","request":"$request","status":$status,"bytes":$body_bytes_sent,"request_time":$request_time}';
  access_log /var/log/nginx/access.log json_combined;
  sendfile on;
  keepalive_timeout 65;
  client_max_body_size 25m;
  include /etc/nginx/conf.d/*.conf;
}

