ALTER TABLE `messages`
  ADD COLUMN `model` VARCHAR(100) NULL,
  ADD COLUMN `input_tokens` INTEGER UNSIGNED NULL,
  ADD COLUMN `output_tokens` INTEGER UNSIGNED NULL,
  ADD COLUMN `total_tokens` INTEGER UNSIGNED NULL;
